[profile.default]
src = "."
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "../circuits/target" },
    { access = "read-write", path = "/tmp/" }
]
ffi = true

# Optimizer settings
optimizer = true
optimizer_runs = 200
#via_ir = true
